### ISSUE TITLE
Missing .SQL file

### ISSUE THREAD

**Issue by hillarybander** [priyasubburaj05/pharmacy-management-system#1]
Dear Author, it seems i cant find the SQL file file for your project.
i am kindly requesting that you upload one , i wish to get an idea of your database architecture

**Comment by priyasubburaj05** [comment]
Hi @hillarybander I have added 2 new files one in _.ods_ format and other in _sql_ format as per your request :))

**Comment by hillarybander** [comment]
Hi @priyasubburaj05 thank you very much, i appreciate the quick response.
i have succesfully downloaded and imported the db, 

Best Regards
